const CHANNELS = [
  { name: "PewDiePie", handle: "PewDiePie" },
  { name: "Hungry Horse Poker", handle: "hungryhorsepoker" },
  { name: "T6", handle: "timesix_" },
  { name: "Alex Hormozi", handle: "AlexHormozi" },
  { name: "Leila Hormozi", handle: "leilahormozi" },
  { name: "Andrew Huberman", handle: "hubermanlab" },
  { name: "The Diary Of A CEO", handle: "TheDiaryOfACEO" },
  { name: "Jack Neel", handle: "jackneel" },
  { name: "Snook", handle: "Snook_YT" },
  { name: "Speeed", handle: "SpeeedCo" },
  { name: "Michael Reeves", handle: "MichaelReeves" },
  { name: "Brad Owen", handle: "BradOwenPoker" },
  { name: "Doug Vargo", handle: "dougvargo_" },
  { name: "AI Search", handle: "theAIsearch" },
  { name: "Vivec", handle: "Vivec" },
  { name: "Meghan & Jack", handle: "meghanandjack" },
  { name: "Basically Homeless", handle: "BasicallyHomeless" },
  { name: "F1nn5terLIVE", handle: "F1nn5terLIVE" },
  { name: "8-BitRyan", handle: "8BitRyan" },
  { name: "Jesse Eckel", handle: "jesseeckel2" },
  { name: "DougDougDoug", handle: "dougdougdoug" },
  { name: "DougDoug", handle: "DougDoug" },
  { name: "Jordan B Peterson", handle: "JordanBPeterson" },
  { name: "Ryan Trahan", handle: "ryan" },
  { name: "Brew", handle: "Brew" },
  { name: "SQUEEZIE", handle: "Squeezie" },
  { name: "Tabbes", handle: "Tabbes" },
  { name: "scottimig", handle: "scottimig" },
  { name: "scottim09", handle: "scottim09" },
  { name: "Nexpo", handle: "Nexpo" },
  { name: "Gamingwith NCK", handle: "gamingwithnck7447" },
  { name: "Felix's Toys Review", handle: "felixstoysreview403" },
  { name: "In The World Of AI", handle: "intheworldofai" },
];
